### ISSUE TITLE
Error: Cannot find module '../../specification/others'

### ISSUE THREAD

**Issue by JamesHenry** [MunifTanjim/node-bitbucket#1]
Thanks a lot for starting this project off!

It seems right now you are not publishing the `specifications/` dir (in your `package.json` you have `  "files": ["src", "dist/*.js"]`), and this cause the library to immediately crash as it is being required by things within `src`.

Code to reproduce is literally just:

```
const BitBucket = require('bitbucket');
```

I'm happy to submit a PR if the change is just a matter of also publishing that dir.

**Comment by MunifTanjim** [comment]
@JamesHenry Thanks a lot for noticing that! :smiley: 

The plan is to split the `specification` folder and routes generation process to a separate repository. So, the current workaround is to include the necessary information in the `src` folder during the specification generation process.
