### ISSUE TITLE
Add `pagelen` parameter to repositories.list API

### ISSUE THREAD

**Issue by RomanIsko** [MunifTanjim/node-bitbucket#10]
Is there any method how can I specify additional parameter for `repositories.list` method? I need to add `pagelen` parameter e.g. `pagelen=50`. Please add such possibility to API. Thanks

**Comment by MunifTanjim** [comment]
Does Bitbucket API accepts the `pagelen` parameter?

ref: https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D#get

**Comment by RomanIsko** [comment]
There is nothing about that parameter in documentation but it's actually works. You may test it with the following requests
https://api.bitbucket.org/2.0/repositories/romanisko
https://api.bitbucket.org/2.0/repositories/romanisko?pagelen=1

As you can see, there is `"next": "https://api.bitbucket.org/2.0/repositories/romanisko?pagelen=1&page=2"` and only one repository in JSON response for second request.

**Comment by MunifTanjim** [comment]
available from [bitbucket@1.5.0](https://www.npmjs.com/package/bitbucket/v/1.5.0) 🎉
