### ISSUE TITLE
Support getDefaultReviewers for repositories - {workspace} - {repo_slug} - default-reviewers endpoint

### ISSUE THREAD

**Issue by tasansga** [MunifTanjim/node-bitbucket#105]
Currently getDefaultReviewer for a single user is implemented, but getDefaultReviewers to get a list of all reviewers for a given repository is missing.

**Comment by MunifTanjim** [comment]
Are you looking for `listDefaultReviewers` - https://bitbucketjs.netlify.app/#api-repositories-repositories_listDefaultReviewers ?

**Comment by tasansga** [comment]
Oh yes, that’s it. Thanks a lot and sorry for the fuss!
