### ISSUE TITLE
Prepare for username changes

### ISSUE THREAD

**Issue by jdoklovic** [MunifTanjim/node-bitbucket#11]
Atlassian is changing how APIs deal with usernames.

see: https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-gdpr/

**Comment by MunifTanjim** [comment]
@jdoklovic
I read the article a couple weeks ago. But the API specification is not changed yet :thinking: 

Could you provide any insight about if it will change (removal of deprecated endpoints and addition of new endpoints) after _12 April 2019_ **all at once** or will there be some kind of deprecation tag first and then removal?

**Comment by jdoklovic** [comment]
I believe it's going to be an all at once deal.  I'll check with the bitbucket team and get back with you

**Comment by erikvanzijst** [comment]
Not much will change between now and April. Everything should already be in place to allow clients to move away from usernames today. The only thing that happens in April is that the username field will disappear from all responses and URLs.

If you have any specific concerns or questions around how to effectively use the API without usernames, please let me know.

**Comment by MunifTanjim** [comment]
Thanks for the information. :+1: 

I'll add a warning message in the library that is logged at startup.

**Comment by MunifTanjim** [comment]
[`v1.7.0`](https://www.npmjs.com/package/bitbucket/v/1.7.0) released with Bitbucket Cloud API Change Notice...

![bitbucket cloud api change notice](https://user-images.githubusercontent.com/8050659/50382152-02fc7680-06c3-11e9-9833-d8fe3029676f.png)

:tada:
