### ISSUE TITLE
Add/delete pull-request watch

### ISSUE THREAD

**Issue by tim-jagenberg-piscada** [MunifTanjim/node-bitbucket#111]
As a developer I want to be able to remove watches from a pull-requests in order for our automation-bot to not receive e-mail updates for pull-requests it commented on.

The API is available on the REST side but not expose in this library:
https://docs.atlassian.com/bitbucket-server/rest/7.16.0/bitbucket-rest.html#idp363

**Comment by MunifTanjim** [comment]
This library is actually a wrapper for Bitbucket Cloud API v2: https://developer.atlassian.com/bitbucket/api/2/reference/

Bitbucket Server uses the old v1 APIs.
