### ISSUE TITLE
Add support for API to fetch pull requests based on a commit hash

### ISSUE THREAD

**Issue by prkb** [MunifTanjim/node-bitbucket#13]
This API was added recently to get a list of all pull requests as part of which this commit was reviewed. Can this be added to the library as well?
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/commits/%7Bcommit%7D/pullrequests

**Comment by MunifTanjim** [comment]
Added on [`v1.6.0`](https://www.npmjs.com/package/bitbucket/v/1.6.0) :tada: 

```http
GET             /repositories/{username}/{repo_slug}/commit/{commit}/pullrequests
GET POST        /repositories/{username}/{repo_slug}/deploy-keys
DELETE GET PUT  /repositories/{username}/{repo_slug}/deploy-keys/{key_id}
GET             /repositories/{username}/{repo_slug}/environments/
POST            /repositories/{username}/{repo_slug}/environments/{environment_uuid}/changes/
```
