### ISSUE TITLE
Feature: Listing all repository permissions for a workspace

### ISSUE THREAD

**Issue by PezCoder** [MunifTanjim/node-bitbucket#130]
Hey! I wanted to know if there is any plan to support this API which lets you get repository permissions for a workspace:

https://developer.atlassian.com/cloud/bitbucket/rest/api-group-workspaces/#api-workspaces-workspace-permissions-repositories-get

This API is especially useful when a use case requires you to fetch all collaborators for a repository.

I would be happy to raise a PR if you're interested.

**Comment by MunifTanjim** [comment]
`v2.9.0` should have those endpoints.

**Comment by PezCoder** [comment]
Oh wow, lucky me that you just released it! 🎉 Closing this.
