### ISSUE TITLE
Help with filter queries and /deployments

### ISSUE THREAD

**Issue by dgsangoma** [MunifTanjim/node-bitbucket#134]
I'm trying to use the `deployments.list` method with filter and sort params. After finding the following comment:

https://jira.atlassian.com/browse/BCLOUD-18729?focusedId=3179095&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3179095

I think it's possible to do this, but I think it's necessary not to include `q=` at the beginning of the query in the request URL. Is there a way to see additional debug info for the request the library makes to confirm what URL it uses?

**Comment by MunifTanjim** [comment]
You can see all the information about the request like this:

```js
bitbucket.deployments
  .list({
    workspace: '<WORKSPACE>',
    repo_slug: '<REPO>',
    sort: '-state.completed_on',
  })
  .then((res) => {
    console.log('res', res)
  })
  .catch((err) => {
    console.error(err)
  })
```
