### ISSUE TITLE
How do I list pull request of repo for specific team ?

### ISSUE THREAD

**Issue by therepo90** [MunifTanjim/node-bitbucket#15]
Im trying bitbucket.pullrequests.list({repo_slug: 'reponame'}) but it tries [my_username]/repo 
instead of [my_team]/repo ?

**Comment by MunifTanjim** [comment]
- Official Docs: [`/2.0/repositories/{username}/{repo_slug}/pullrequests`](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests)
- Library Docs: [`pullrequests.list`](https://bitbucketjs.netlify.com/#api-pullrequests-pullrequests_list) or [`repositories.listPullRequests`](https://bitbucketjs.netlify.com/#api-repositories-repositories_listPullRequests)

You need to pass the `username` parameter.
