### ISSUE TITLE
listPullRequestsActivityLog does not accept stated parameters

### ISSUE THREAD

**Issue by RafalSkorka** [MunifTanjim/node-bitbucket#21]
I wanted to get more than 10 entries in the activity log, but the available functions have issues:

[`bitbucket.pullrequests.getActivityLog`](https://bitbucketjs.netlify.com/#api-pullrequests-pullrequests_getActivityLog) does not accept `pagelen` parameter. The [documentation](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/%7Bpull_request_id%7D/activity) does not state `pagelen` is a possible parameter but it works when passed manually.

[`bitbucket.repositories.listPullRequestsActivityLog`](https://bitbucketjs.netlify.com/#api-repositories-repositories_listPullRequestsActivityLog) is described to accept `pull_request_id` as a required (!) parameter, but it is ignored and not sent to BitBucket API.   The [documentation](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/pullrequests/activity) states `pull_request_id` as path parameter, but it's a mistake there since it does not exist on this path. `pagelen` is accepted and sent to API.

Could you extend `getActivityLog` so it accepts `pagelen` parameter?

**Comment by MunifTanjim** [comment]
@RafalSkorka Thanks for reporting this.

This should be fixed on v[1.10.0](https://www.npmjs.com/package/bitbucket/v/1.10.0) :tada: 

Also, note that the following methods were renamed to better reflect their operations:

**commits**
```
fetchAll -> listAlt
listFor -> listAt
fetchAllFor ->listAtAlt
```

**pullrequests**
```
getForCommit -> listForCommit
getActivityLog -> listActivities
listActivityLog -> listActivitiesForRepo
```

**repositories**
```
getPullrequestsForCommit -> listPullrequestsForCommit
fetchAllCommits -> listCommitsAlt
listCommitsFor -> listCommitsAt
fetchAllCommitsFor -> listCommitsAtAlt
getPullRequestActivityLog -> listPullRequestActivities
listPullRequestsActivityLog -> listPullRequestActivitiesForRepo
getSrcMainRoot -> readSrcRoot
getSrc -> readSrc
```

**snippets**
```
deleteCommit -> deleteAt
getCommit -> getAt
updateCommit -> updateAt
listCommitsFor -> getCommit
```

**source**
```
getMainRoot -> readRoot
get -> read
```

**teams**
```
listMembers -> getAllMembers
```

Bitbucket's API documentation has a lot of quirks. Sometimes it's not clear what an endpoint does without trying it, that's why a lot of method names were totally wrong or not clear about what they do.

Hope this release fixes some of them. And sorry for the inconvenience.

**Comment by RafalSkorka** [comment]
Thank you! Now it works!
Although I have this warning printed for some reason:
`[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4`

**Comment by MunifTanjim** [comment]
Don't worry about it. It's a message from one of the dependencies.

I'll be closing this issue as it's solved.
