### ISSUE TITLE
Sending incorrect `accepts` value to pipelines logs endpoint

### ISSUE THREAD

**Issue by rundquist** [MunifTanjim/node-bitbucket#25]
`Bitbucket.pipelines.getStepLog` throws `HTTPError: Cannot read property 'message' of undefined`. This is happening because the server is returning a 406 because the request specifies an `accepts` value of `application/json` while the endpoint only returns `application/octet-stream`.

**Comment by rundquist** [comment]
Created https://github.com/MunifTanjim/node-bitbucket/pull/23 to fix the issue.

**Comment by MunifTanjim** [comment]
@rundquist @jdoklovic 

This should be fixed on v`1.11.0`

Before you update to the latest version... I've unfortunately did a stupid thing in the last 3 minor version updates (`1.8.0`, `1.9.0` and `1.10.0`). Those versions contain some api name changes (which would break the scripts that use them). This type of mistakes won't happen again from my part.

You can find the complete list of changes in this file: [v1_API_NAME_CHANGES.md](https://github.com/MunifTanjim/node-bitbucket/blob/master/v1_API_NAME_CHANGES.md)

**Comment by rundquist** [comment]
Yup, it was pretty painless. Thanks for getting this merged in so quickly!
