### ISSUE TITLE
Can't use the client with BitBucket Server

### ISSUE THREAD

**Issue by kguirguis** [MunifTanjim/node-bitbucket#29]
Can't use the client with BitBucket Server. Not sure if I'm supposed to specify anything other than the baseUrl differently for it to work? It seems like the API's are different.

**Comment by MunifTanjim** [comment]
I don't know much about Bitbucket Server. This library was generated from the public api specification for Bitbucket Cloud.

I assumed they have similar api endpoints :thinking: 

Is that not the case?

**Comment by kguirguis** [comment]
Hey, yeah they have different endpoints 😅

**Comment by MunifTanjim** [comment]
Guess REST API v2 is not gonna come to Bitbucket Server (https://community.atlassian.com/t5/Bitbucket-questions/REST-API-v2-for-Bitbucket-Server/qaq-p/941689)

In that case, I'm gonna update the README.md

**Comment by kguirguis** [comment]
Alright sounds good, thanks !
