### ISSUE TITLE
GDPR Support

### ISSUE THREAD

**Issue by yuliabaron** [MunifTanjim/node-bitbucket#30]
Hi,

Does your `readSrc` endpoint support getting account_id or uuid as username? Based on the Bitbucket API, it should work. I can call smth like `https://api.bitbucket.org/2.0/repositories/%7B<UUID>%7D/<repoSlug>/src/<branch>/<file>` and get file content back. However it seems that 
`this.api.repositories.readSrc({
      repo_slug,
      username: uuid,
      node,
      path,
    });`

Fails with     
`HTTPError: Repository <uuid>/<repoSlug> not found
      at getData.then.error (node_modules/bitbucket/src/request/fetch.js:53:17)`

**Comment by MunifTanjim** [comment]
Can you share the console output when you run the script with `DEBUG=bitbucket` environment variable? (e.g. `DEBUG=bitbucket node script-file.js`)
