### ISSUE TITLE
implementing the hideNotice in the clientOptions doesn't appear to work

### ISSUE THREAD

**Issue by ejlax** [MunifTanjim/node-bitbucket#34]
I am trying to have it stop the annoying Bitbucket API logs, and i see that you have a `logNotice()` function the will get removed if you have a `this.options.hideNotice` set. I have tried the following to no joy:
```
const clientOptions: Bitbucket.Options = {
  options: {
    hideNotice: true
  }
}

const bitbucket = new Bitbucket(clientOptions)
```

If also tried:

```
const clientOptions: Bitbucket.Options = {
    hideNotice: true
}
```

but `hideNotice` isn't a supported Type on Bitbucket.Options.

Any insight would be super helpful. Thanks in advance

**Comment by ejlax** [comment]
In the meantime, i just extended your interface to allow me to do this via my typescript code:

```export interface ExtBitbucketOptions extends Bitbucket.Options {
  hideNotice: boolean
}```

This seems to have worked.

**Comment by MunifTanjim** [comment]
Sorry about that. The `hideNotice` option was added to resolve #17, but the TS types file was not updated. Will update and publish a update soon @ejlax

**Comment by ejlax** [comment]
Thank you very much!
