### ISSUE TITLE
Queries is not working on listRepositories

### ISSUE THREAD

**Issue by rafaels-dev** [MunifTanjim/node-bitbucket#37]
Hi!

I'm trying to get repositories using _query_, but isn't working. The API is returning all repositories of this team/user instead just my filtered repo.

See my code:
```
const repositories = await bitbucket.teams.listRepositories({ pagelen: 2, page: 1, q: 'full_name="repo1"', username });
```
Is my syntax correct? I'm following patterns described on [Bickbucket Filtering and Sorting documentation](https://developer.atlassian.com/bitbucket/api/2/reference/meta/filtering).

Thanks!

**Comment by MunifTanjim** [comment]
Which version of the library are you using?

Can you show me the output of your script with `DEBUG=bitbucket` environment variable set?

**Comment by MunifTanjim** [comment]
Seems like for requests to the [`/teams/{username}/repositories`](https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams/%7Busername%7D/repositories) endpoint Bitbucket API does these:
- Ignores the query parameters 
- Returns response for the `/repositories/{username}` endpoint instead

So, I can't do anything about it... ¯\\\_(ツ)_/¯ 

Try using the `/repositories/{username}` endpoint (`bitbucket.repositories.list`), it respects the query parameters.

**Comment by rafaels-dev** [comment]
URL of DEBUG=bitbucket is `https://api.bitbucket.org/2.0/teams/minutrade/repositories?page=1&pagelen=2&q=full_name%3D%22bla%22`. The parameters are correct. 

I changed to `bitbucket.repositores.list` and it works fine. Thanks!
