### ISSUE TITLE
Add User to Repo / Privileges API

### ISSUE THREAD

**Issue by AnalogJ** [MunifTanjim/node-bitbucket#4]
Hey,
Do you know if its possible to add a user/collaborator to a repo using the bitbucket API? Its definitely possible via the web-ui, but I can't seem to find it in the v2 documentation.

**Comment by MunifTanjim** [comment]
If you can't find it in the documentation, there is no chance it's gonna be in this library. Because, this library is generated from the official documentation itself.

So currently, as far as I know, it's not possible.
