### ISSUE TITLE
fields support

### ISSUE THREAD

**Issue by RafalSkorka** [MunifTanjim/node-bitbucket#41]
Bitbucket allows to specify **fields** as a query parameter and that limits the response fields. However, this option is not available here.
See the docs: https://developer.atlassian.com/bitbucket/api/2/reference/meta/partial-response
eg. if I add 

```
        "fields": {
          "in": "query",
          "type": "string"
        },
```
to routes.json -> listTags then it properly works by adding the fields parameter using a call like:

```
        let {
            data,
            headers
        } = await bitbucket.refs.listTags({
            repo_slug: 'myrepo',
            username: 'myteam',
            pagelen: 20,
            sort: "-name",
            fields: "values.name,values.target.hash"
        });
```

Could you add "fields" parameter to queries?

**Comment by MunifTanjim** [comment]
@RafalSkorka Would you be willing to try the beta version?

**docs**: https://next--bitbucketjs.netlify.com/
**npm**: https://www.npmjs.com/package/bitbucket/v/2.0.0-beta.1
**source**: https://github.com/MunifTanjim/node-bitbucket/tree/next

It already has that feature.

**Comment by RafalSkorka** [comment]
Seems to be working fine in 2.0. Thanks!

**Comment by MunifTanjim** [comment]
`bitbucket@2.0.0` is published :tada:
