### ISSUE TITLE
Not able to submit a body to UpdateBranchingModelSettings

### ISSUE THREAD

**Issue by folofse** [MunifTanjim/node-bitbucket#45]
"version": "1.15.2"

I guess it should be possible to update the branching models according to 
https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/branching-model/settings#put

But the generated ts code does not accept a body:

```
export type RepositoriesUpdateBranchingModelSettings =
      {
        "repo_slug": string;
        "username": string;
      };
```

**Comment by MunifTanjim** [comment]
Published `v1.16.0` :tada:
