### ISSUE TITLE
updateEnvironment requires a _body parameter

### ISSUE THREAD

**Issue by folofse** [MunifTanjim/node-bitbucket#47]
Hi

I write here instead of creating a PR, basically we need to add a _body to the updateEnvironment

```
"_body": {
  "in": "body",
  "required": true,
  "schema": "DeploymentEnvironment",
  "type": "any"
},
```

It's not documented in the API´s 

https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/environments/%7Benvironment_uuid%7D/changes/ )

But this endpoints takes a body with changes like this

```
{
  "change":{
    "name":"My Environment name",
  }
}
```
I don't think we can change its type like Test|Staging|Production since this don't seems to be able to change it in Bitbucket dashboard either.

**Comment by MunifTanjim** [comment]
released `v1.17.0` :tada:
