### ISSUE TITLE
bitbucket.users.get() throwing error now...

### ISSUE THREAD

**Issue by rlyle** [MunifTanjim/node-bitbucket#56]
This code has been working for ages, but lately we've been getting the following error now when trying to get users from bitbucket..

HTTPError: richard_lyle at getData.then.error (/var/task/node_modules/bitbucket/src/request/fetch.js:53:17) at process._tickCallback (internal/process/next_tick.js:68:7) Message: richard_lyle

This is the code we are using to grab a user by their username:
```
    getUser(username) {
        return new Promise((resolve, reject) => {
            bitbucket.users.get({username}).then(({data}) => {
                log.debug("getUser result:", data );
                resolve(data);
            }).catch((err) => {
                log.error("getUser error:", err );
                reject(err);
            })
        })
    }


```

**Comment by MunifTanjim** [comment]
Which version of `bitbucket` are you using?

can you try running your script with `DEBUG=bitbucket` environment variable set and paste the output here?

**Comment by rlyle** [comment]
I switched over to this, and now it's working..

```
   getUser(username) {
        return new Promise((resolve, reject) => {
            bitbucket.teams.get({username}).then(({data}) => {
                log.info("get team members:", data );
                resolve(data);
            }).catch((err) => {
                log.error("getUser error:", err );
                reject(err);
            })
        })
    }
```
