### ISSUE TITLE
How to use with Bitbucket Server?

### ISSUE THREAD

**Issue by SimplySeth** [MunifTanjim/node-bitbucket#6]
Is this only for cloud? 
I don't see where to specify the url. 
Thanks.

**Comment by MunifTanjim** [comment]
The documentation is missing a few things. Sorry about that. This library should work with any BitBucket instances as long as the API endpoints are the same.

Here's how you define a custom `baseUrl`:

```js
const bitbucket = new BitBucket({
  baseUrl: 'https://api.example.com/2.0'
})
```

Let me know if that works.
