### ISSUE TITLE
Readme has an invalid example

### ISSUE THREAD

**Issue by ItamarM** [MunifTanjim/node-bitbucket#63]
See [here](https://github.com/MunifTanjim/node-bitbucket/blob/master/README.md#examples)

```js
bitbucket.repositories
  .list({ username: 'MunifTanjim' })
  .then(({ data }) => console.log(data.values))
  .catch((err) => console.error(err))
```

I think that you meant listGlobal

**Comment by MunifTanjim** [comment]
Yeah, it's invalid for the current version. The `username` should be `workspace`.

**Comment by ItamarM** [comment]
@MunifTanjim thanks. Do you want me to close this issue and wait for a stable version?
I saw many breaking changes and wondered if it is WIP.

**Comment by MunifTanjim** [comment]
> Do you want me to close this issue?

let's keep it open until the README file is fixed.

> wait for a stable version? I saw many breaking changes and wondered if it is WIP.

this is a stable version and the documentation is available at https://bitbucketjs.netlify.app
