### ISSUE TITLE
Some parts of api are locked out while using lib because of deprecation of /teams and some /user api endpoints

### ISSUE THREAD

**Issue by DamianRB** [MunifTanjim/node-bitbucket#66]
https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/

**Comment by MunifTanjim** [comment]
Just released [`v2.3.0`](https://www.npmjs.com/package/bitbucket/v/2.3.0) with the latest API Specifications.

**Comment by DamianRB** [comment]
Fastest "by the way" resolution ;)
