### ISSUE TITLE
Main endpoint for workspaces is missing

### ISSUE THREAD

**Issue by NicolasReibnitz** [MunifTanjim/node-bitbucket#67]
First of all: thank you! This is really great to have!

But I cannot seem to get a list of my workspaces. Like here:
https://api.bitbucket.org/2.0/workspaces/
(https://developer.atlassian.com/bitbucket/api/2/reference/resource/workspaces).

Or am I missing something?

Thanks in advance!

**Comment by MunifTanjim** [comment]
Thanks for reporting this. Yes, some of those endpoints are missing in the current release.

https://github.com/MunifTanjim/node-bitbucket/blob/master/specification/extras/endpoint-names.json#L1374-L1445

I'll add those as soon as possible.

**Comment by NicolasReibnitz** [comment]
Alright, I guess we still have a little time left till October 14th. :)

Thanks a lot for clarifying!

**Comment by MunifTanjim** [comment]
Just published [`v2.4.0`](https://www.npmjs.com/package/bitbucket/v/2.4.0) :tada:

**Comment by NicolasReibnitz** [comment]
Way to go!! Thank you very much!
