### ISSUE TITLE
type not found `FormData` in  bitbucket.d.ts in declaration

### ISSUE THREAD

**Issue by belangovan** [MunifTanjim/node-bitbucket#72]
Missing FormData types in declaration modules kindly update it

node_modules/bitbucket/lib/bitbucket.d.ts:1946:12 - error TS2304: Cannot find name 'FormData'.

1946     _body: FormData
                ~~~~~~~~

node_modules/bitbucket/lib/bitbucket.d.ts:1987:12 - error TS2304: Cannot find name 'FormData'.

1987     _body: FormData
                ~~~~~~~~

node_modules/bitbucket/lib/bitbucket.d.ts:2927:12 - error TS2304: Cannot find name 'FormData'.

2927     _body: FormData
                ~~~~~~~~

node_modules/bitbucket/lib/bitbucket.d.ts:2947:12 - error TS2304: Cannot find name 'FormData'.

2947     _body: FormData
                ~~~~~~~~

node_modules/bitbucket/lib/bitbucket.d.ts:3035:13 - error TS2304: Cannot find name 'FormData'.

3035     _body?: FormData | Schema.AnyObject
                 ~~~~~~~~

node_modules/bitbucket/lib/bitbucket.d.ts:4274:13 - error TS2304: Cannot find name 'FormData'.

4274     _body?: FormData | Schema.AnyObject

**Comment by belangovan** [comment]
Kindly update types

**Comment by MunifTanjim** [comment]
Kindly add `dom` to `lib` in your `tsconfig.json` file:

```json
{
    "compilerOptions": {
        "lib": [
            "dom"
        ]
    }
}
```

**Comment by belangovan** [comment]
thanks, updated. invalid bug
