### ISSUE TITLE
Basic authentication not working

### ISSUE THREAD

**Issue by shanekoss** [MunifTanjim/node-bitbucket#75]
Thanks for this library - very useful!

Having an issue with basic authentication - have it set up like the documentation:

```
const clientOptions = {
  baseUrl: "https://api.bitbucket.org/2.0",
  request: {
    timeout: 10
  },
  auth: {
    username: "*****",
    password: "*************"
  }
};

const bitbucket = new Bitbucket(clientOptions);

bitbucket.repositories
  .listGlobal()
  .then(({ data }) => console.log(data.values))
  .catch(err => console.error(err));
```

I get this error:

TypeError: Cannot read property 'headers' of undefined

from index.umd.js:15:464

Any ideas?

Same credentials are working with Postman.

Thanks!

**Comment by AdamSalma** [comment]
I am also getting this error. +1

**Comment by MunifTanjim** [comment]
I've tested it in Node.js and it's working alright. Are you using it in Browser? 🤔

**Comment by shanekoss** [comment]
@MunifTanjim thanks so much for taking a look.  I'm actually using it node.js as well.  

OSX 10.15.3
Node 10.17.0

Let me know if anything you'd like to me to change or try here.

Cheers.

**Comment by MunifTanjim** [comment]
How is your project setup? 🤔 It shouldn't use `index.umd.js` for Node.js.

**Comment by MunifTanjim** [comment]
Hey @shanekoss , can you try doing:

```

**Comment by shanekoss** [comment]
@MunifTanjim - thanks.  doh!  that was it.

**Comment by AdamSalma** [comment]
Fixed the solution on my end too, thanks!

Can we update the README.md to reflect this? I think we all arrived here from copying parts of the code listed in there, it would help to stop people asking the same question
