### ISSUE TITLE
listCommits has revision parameter required (since version 2.5.0)

### ISSUE THREAD

**Issue by tovbinm** [MunifTanjim/node-bitbucket#90]
For some reason `listCommits` has `revision` [parameter required](https://github.com/MunifTanjim/node-bitbucket/blob/master/src/plugins/register-api-endpoints/routes.json#L3051) but it's not the way on the official API - https://bitbucketjs.netlify.app/#api-repositories-repositories_listCommits

Please fix.

**Comment by MunifTanjim** [comment]
Bitbucket's API Specification had that parameter as required when this library was last released. They fixed it after that.

Released `v2.6.0` built from latest API Specification. Should be fixed now.

**Comment by tovbinm** [comment]
Thank you!
