### ISSUE TITLE
Remove console logging (2.4.2, 2.5.1, 2.6.1)

### ISSUE THREAD

**Issue by tovbinm** [MunifTanjim/node-bitbucket#92]
```
console.log:
     BITBUCKET CLOUD API LATEST UPDATES:  https://developer.atlassian.com/cloud/bitbucket
```

I tried passing `notice: false` into `clientOptions` but no luck:
```typescript
import {Bitbucket} from 'bitbucket';

const clientOptions = {
  notice: false,
  auth: {
    username: cfg.bitbucketUsername,
    password: cfg.bitbucketPassword,
  },
};
const bitbucket = new Bitbucket(clientOptions);
```

**Comment by MunifTanjim** [comment]
Can not reproduce this one.  🤔

**Comment by tovbinm** [comment]
Do I need to import & apply the plugins somehow?

**Comment by MunifTanjim** [comment]
No, your example code looks alright. It shouldn't print that notice.

Can you try putting that example code in a separate file and run only that single file with node? Does it still print the notice?

**Comment by tovbinm** [comment]
My bad! Works as expected. Thanks.
